FRONTENDBOOTCAMP-13th/JS-10-Coding-Dreamtree-Training-Center

test-songah.js

✅ Test: PR 테스트

---

testHyunsoo.js

Hyunsoo PR 테스트

---

test-youngjune.js

- Github PR 테스트 w. 용쌤 Close #5
- [] 새로운 기능 추가
- [] 버그 수정
- [] CSS 등 사용자 UI 디자인 변경
- [] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [] 코드 리팩토링
- [] 주석 추가 및 수정
- [] 테스트 추가, 테스트 리팩토링
- [] 빌드 부분 혹은 패키지 매니저 수정
- [] 파일 혹은 폴더명 수정
- [] 파일 혹은 폴더 삭제
resolves #5

PR 테스트 완료했습니다.

---

src/pages/test.html

close#3
- [] 새로운 기능 추가
- [] 버그 수정
- [] CSS 등 사용자 UI 디자인 변경
- [] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [] 코드 리팩토링
- [] 주석 추가 및 수정
- [] 테스트 추가, 테스트 리팩토링
- [] 빌드 부분 혹은 패키지 매니저 수정
- [] 파일 혹은 폴더명 수정
- [] 파일 혹은 폴더 삭제
resolves #3

✅ Test: 초기 설정용 테스트 코드 추가

---

src/components/Sidebar/sidebar.html

- sidebar 컴포넌트 아웃라인 구현 issues #13
- [] 버그 수정
- [] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [] 코드 리팩토링
- [] 주석 추가 및 수정
- [] 문서 수정
- [] 테스트 추가, 테스트 리팩토링
- [] 빌드 부분 혹은 패키지 매니저 수정
- [] 파일 혹은 폴더명 수정
- [] 파일 혹은 폴더 삭제
resolves # 13

✨ feat: Sidebar 컴포넌트 1차 구현

---

src/data/resource.json

개발 리소스 데이터 JSON 파일 추가
Close #27
resolves #27

✨ feat: 개발 리소스 데이터 JSON 파일 추가

---

src/components/Sidebar/Sidebar.ts
src/components/Sidebar/sidebar.html
src/pages/resource.html

Sidebar 페이지 이동 기능 추가
Close #13
- [] 버그 수정
- [] CSS 등 사용자 UI 디자인 변경
- [] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [] 코드 리팩토링
- [] 주석 추가 및 수정
- [] 문서 수정
- [] 테스트 추가, 테스트 리팩토링
- [] 빌드 부분 혹은 패키지 매니저 수정
- [] 파일 혹은 폴더명 수정
- [] 파일 혹은 폴더 삭제
resolves #13

✨ feat: Sidebar 페이지 이동 기능 추가

---

src/components/ResourceCard/resource-card.html
src/pages/resource.html

- resource-card 컴포넌트 수정
- resource 페이지 리팩토링 ( button 태그 -> label & select 태그로 개선 )
- (필요) 선택됐을 때 색상이 변경되는 기능 구현 필요
resolves #29

♻️ refactor : resource-card 컴포넌트 수정 및 resource 페이지 마크업 수정

---

src/pages/resource.html

- 필터링 div 상단 영역 안보이게 위치 조정 및 drop shadow 추가
- '언어' 카테고리 삭제
resolves #34

💄 style: resource UI 수정

---

src/pages/resource.html
src/script/filter.ts
src/types/filter.type.ts

카테고리 필터링 기능 추가
Close #41
카테고리 필터링 기능 추가
resolves #41

✨ feat: 카테고리 필터링 기능 추가

---

src/pages/resource.html
src/script/filter.ts
src/script/resourceRendering.ts

- resourceRendering.ts 에서는 렌더링 기능만 구현하도록 수정했습니다.
- filter.ts 에서는 렌더링된 데이터를 가져와, 필터 기능만 가능하도록 수정했습니다.
- resource.html 에서 필터링 초기화 버튼에 data-roll 속성을 추가했습니다.
- dev, compile 테스트 후 이상 없음!
resolves #45

 🐛 bugfix: filter, resourceRendering 파일 충돌 이슈 해결

---

package-lock.json
package.json
src/main.ts
src/pages/bookmark.html
src/pages/dashboard.html
src/pages/login.html
src/pages/resource.html
src/pages/sample.html
src/script/bookmarkRendering.ts
src/script/header.ts
src/script/login.ts
src/script/resourceRendering.ts
src/service/auth.ts
src/service/bookmark.ts
src/types/bookmark.type.ts
src/types/user.type.ts

로그인 기능 및 북마크 기능을 구현했습니다.
resolves #44

💫 merge: feature/login/hyusoo 브랜치 변경사항 develop 브랜치에 병합

---

index.html
src/components/DailyResources/daily-resources.html
src/components/DailyResources/daily-resources.ts
src/main.ts

- index.html에 DailyResources 컴포넌트 추가
- DailyResources 컴포넌트 구현
resolves #17

✨ feat: DailyResources 컴포넌트 구현

---

src/components/DailyResources/daily-resources.html
src/components/DailyResources/daily-resources.ts
src/pages/dashboard.html
src/script/dailyResources.ts

- DailyResources compile 시 데이터 불러오는 오류 해결
- DailyResources 상세보기 모달 연결
resolves #56

🐛 bugfix: DailyResources compile 오류 해결과 모달 연결

---

src/pages/resource.html

카테고리 필터링 데이터 누락으로 인한 오류 수정
카테고리 필터링 데이터 누락으로 인한 오류 수정
resolves #

✨ feat: 카테고리 필터링 데이터 추가

---

index.html
src/components/Modal/modal.html
src/pages/resource.html

- form의 gap 속성을 제거 후 margin을 이용해서 구현
- 반응형 UI를 위해 media query를 사용하여 모바일 화면에서의 UI 수정
- gird 속성과 flex 속성을 사용하여 반응형 구현
resolves #

🐛 bugfix: 간격 조절 및 반응형 UI 수정

---

index.html
src/pages/bookmark.html
src/pages/resource.html
src/script/resourceRendering.ts

- 전체 페이지 제목/설명 스타일링 통일
- 렌더링 아티클의 설명 스타일링 수정
none

💄 style: 설명 텍스트 추가 및 스타일 통일

---

src/components/Sidebar/sidebar.ts
src/script/bookmarkRendering.ts

비로그인 상태에서 북마크 페이지로 이동하는 링크를 클릭 했을 때, 북마크 페이지로 이동을 하고 alert()이 뜨고, 로그인 페이지로 리다이렉트 되는 버그를 수정함
resolves #73

🐛 bugfix: 북마크 링크 이벤트 수정

---

src/pages/resource.html
src/style.css

- 카테고리, AI, CS 추가
- 기술스택, C++ python등 추가
resolves #

✨ feat: 리소스 페이지 option, value 추가

---

index.html
src/pages/resource.html
src/script/collectionModal.ts

- breakpoint 커스텀 값을 @theme 에서 정의한 변수로 변경
- resource.html 의 모달창 레이아웃이 깨지는 현상 수정
- 모달창 background(backdrop) 컬러 통일
none

💄 style: 모달창 레이아웃 UI 통일

---

index.html
src/pages/bookmark.html
src/pages/login.html
src/pages/resource.html

사이드바가 스크롤이 내려가도 항상 고정되도록 수정
none

🔧 fix: 사이드바 레이아웃 수정

---

index.html
src/pages/resource.html
src/script/modalRendering.ts

🐛 bugfix: 모달 스크롤바 숨김 처리 오류 수정
